### ISSUE TITLE
wishbone-tool doesn't appear to handle concurrent wishbone clients

### ISSUE THREAD

**Issue by zyp** [litex-hub/wishbone-utils#38]
Hi, I observe that if I'm trying to use two wishbone clients at the same time (one script that runs litescope and another python session where I'm poking at some CSRs), the second client will get a socket timeout.

It would be nice if wishbone-tool could handle concurrent clients and arbitrate requests.

**Comment by mithro** [comment]
@xobs - Thoughts?

**Comment by xobs** [comment]
What command are you using to invoke `wishbone-tool`?

It should support concurrent connections, while it cannot currently support multiple instances of `wishbone-tool` running.

**Comment by zyp** [comment]
I'm running `wishbone-tool --vid 0x1209 --pid 0x3443 --server wishbone`. It is connecting to a LUNA-based USB bridge that's implementing the same commands as the ValentyUSB one. This is working fine as long as I'm only trying to connect one client at a time to `wishbone-tool`.

As soon as I'm trying to connect a second client I'm getting errors like this:
```
Traceback (most recent call last):
  File "/Users/zyp/Documents/orbtrace/./scope.py", line 16, in <module>
    analyzer.add_rising_edge_trigger("crossbar_source_valid")
  File "/Users/zyp/Documents/orbtrace/deps/litescope/litescope/software/driver/analyzer.py", line 110, in add_rising_edge_trigger
    self.add_trigger(getattr(self, name + "_o")*0, getattr(self, name + "_m"))
  File "/Users/zyp/Documents/orbtrace/deps/litescope/litescope/software/driver/analyzer.py", line 81, in add_trigger
    if self.trigger_mem_full.read():
  File "/Users/zyp/Documents/orbtrace/deps/litex/litex/tools/remote/csr_builder.py", line 40, in read
    datas = self.readfn(self.addr, length=self.length)
  File "/Users/zyp/Documents/orbtrace/deps/litex/litex/tools/litex_client.py", line 64, in read
    packet = EtherbonePacket(self.receive_packet(self.socket))
  File "/Users/zyp/Documents/orbtrace/deps/litex/litex/tools/remote/etherbone.py", line 369, in receive_packet
    chunk = socket.recv(header_length - len(packet))
socket.timeout: timed out
```

It appears to me that the second connection got accepted, but it's not handling requests.

**Comment by xobs** [comment]
Can you see if `v0.7.9` solves the issue?

**Comment by zyp** [comment]
Yes, now it works. Thanks a lot!
